### ISSUE TITLE
Migration Can Fail if Status Doesn't Exist

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot-app-firewall-models#272]
https://github.com/nautobot/nautobot-app-firewall-models/blob/5b71b14632726da759251069945d0287018e6f49/nautobot_firewall_models/utils/__init__.py#L14-L15

If the configured default status or the defaulted value does not exist, the migration that sources this function can fail.

**Comment by gsnider2195** [comment]
`["Active", "Staged", "Decommissioned"]` statuses are referenced in multiple migrations. Do these need to be documented as statuses that are required for this app and do we need to create them in the migrations and at app startup?

@Kircheneer can you provide some feedback?

**Comment by gsnider2195** [comment]
> `["Active", "Staged", "Decommissioned"]` statuses are referenced in multiple migrations. Do these need to be documented as statuses that are required for this app and do we need to create them in the migrations and at app startup?
> 
> @Kircheneer can you provide some feedback?

For context, all of the models in this app have status marked as a **required** field.

**Comment by smk4664** [comment]
This is common in Nautobot for models to have a required status field, but what is not common is having the `default` filled out for a Status. Statuses can be added/removed by Platform Admins. I think we should take the approach that Nautobot does by allowing Statuses to be deleted. https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/status/?h=statuses#customizing-statuses 

I have seen a pattern where Apps provide some statuses to get started, and maybe we keep some of this in, but I vote removing the `default` argument.

**Comment by gsnider2195** [comment]
After discussion we decided that we will move the logic out of the various migrations that was associating the firewall model content types to the `["Active", "Staged", "Decommissioned"]` statuses and move this into a post-migrate signal. This signal will skip any of these statuses that are not already present.

We will continue to create the statuses that are defined in the plugin configuration (`allowed_status` and `default_status`) since it is required for the app to work but will remove the default status altogether in a future major release.
